from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path

from support import run_cli


class AiCliTests(unittest.TestCase):
    def test_ai_create_and_update(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            cwd = Path(tmp)
            self.assertEqual(run_cli(cwd, "init").returncode, 0)

            script = (
                "import json,sys;_ = sys.stdin.read();"
                "print(json.dumps({"
                "'description':'AI generated role',"
                "'role_prompt':'You handle {{task}} for {{specific_to}}.',"
                "'instructions':'Return a plan and tests for {{task}}.',"
                "'scope':'specific',"
                "'specific_to':'checkout-service',"
                "'profile':'default'"
                "}))"
            )
            add_profile = run_cli(
                cwd,
                "profile",
                "add",
                "mock-ai",
                "--command",
                sys.executable,
                "--arg=-c",
                "--arg",
                script,
                "--prompt-mode",
                "stdin",
            )
            self.assertEqual(add_profile.returncode, 0, add_profile.stderr)

            created = run_cli(
                cwd,
                "ai",
                "Create a QA role for checkout",
                "--name",
                "ai-role",
                "--runner-profile",
                "mock-ai",
                "--format",
                "yaml",
            )
            self.assertEqual(created.returncode, 0, created.stderr)
            created_data = json.loads(run_cli(cwd, "show", "ai-role").stdout)
            self.assertEqual(created_data["format"], "yaml")
            self.assertEqual(created_data["scope"], "specific")
            self.assertEqual(created_data["specific_to"], "checkout-service")

            updated = run_cli(
                cwd,
                "ai",
                "Make this a general planning role",
                "--name",
                "ai-role",
                "--runner-profile",
                "mock-ai",
                "--scope",
                "general",
                "--format",
                "json",
            )
            self.assertEqual(updated.returncode, 0, updated.stderr)
            updated_data = json.loads(run_cli(cwd, "show", "ai-role").stdout)
            self.assertEqual(updated_data["format"], "json")
            self.assertEqual(updated_data["scope"], "general")
            self.assertNotIn("specific_to", updated_data)

    def test_ai_auto_name_from_request(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            cwd = Path(tmp)
            self.assertEqual(run_cli(cwd, "init").returncode, 0)

            script = (
                "import json,sys;_ = sys.stdin.read();"
                "print(json.dumps({"
                "'description':'Generated by AI',"
                "'role_prompt':'Do {{task}}',"
                "'instructions':'Steps for {{task}}',"
                "'scope':'general',"
                "'specific_to':None,"
                "'profile':'default'"
                "}))"
            )
            add_profile = run_cli(
                cwd,
                "profile",
                "add",
                "mock-ai",
                "--command",
                sys.executable,
                "--arg=-c",
                "--arg",
                script,
                "--prompt-mode",
                "stdin",
            )
            self.assertEqual(add_profile.returncode, 0, add_profile.stderr)

            created = run_cli(
                cwd,
                "ai",
                "I want to create a profile with roles for checkout reliability",
                "--runner-profile",
                "mock-ai",
            )
            self.assertEqual(created.returncode, 0, created.stderr)
            self.assertIn("Created template `create-profile-roles-checkout-reliability`", created.stdout)
            self.assertIn(
                "create-profile-roles-checkout-reliability.json",
                run_cli(cwd, "list").stdout,
            )

    def test_ai_tolerates_null_like_optional_values(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            cwd = Path(tmp)
            self.assertEqual(run_cli(cwd, "init").returncode, 0)

            script = (
                "import json,sys;_ = sys.stdin.read();"
                "print(json.dumps({"
                "'description':'Generated by AI',"
                "'role_prompt':'Do {{task}}',"
                "'instructions':'Steps for {{task}}',"
                "'scope':'general',"
                "'specific_to':'None',"
                "'profile':'null',"
                "'repeat_for':'None',"
                "'repeat_every':'null'"
                "}))"
            )
            add_profile = run_cli(
                cwd,
                "profile",
                "add",
                "mock-ai",
                "--command",
                sys.executable,
                "--arg=-c",
                "--arg",
                script,
                "--prompt-mode",
                "stdin",
            )
            self.assertEqual(add_profile.returncode, 0, add_profile.stderr)

            created = run_cli(cwd, "ai", "Create a reusable role", "--name", "nullish-role", "--runner-profile", "mock-ai")
            self.assertEqual(created.returncode, 0, created.stderr)
            payload = json.loads(run_cli(cwd, "show", "nullish-role").stdout)
            self.assertEqual(payload["scope"], "general")
            self.assertNotIn("profile", payload)
            self.assertNotIn("specific_to", payload)
            self.assertNotIn("repeat_for", payload)
            self.assertNotIn("repeat_every", payload)


if __name__ == "__main__":
    unittest.main()
